#!/usr/bin/env ruby

require 'optparse'
require 'captains_mistress/app'

args = ARGV.clone

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: captains_mistress [options]'

  opts.on('-v', '--[no-]verbose', 'Run verbosely') do |v|
    options[:verbose] = v
  end

  opts.on('--width N', Integer, "Set width of the board, Default 7") do |n|
    options[:width] = n
  end

  opts.on('--height N', Integer, "Set height of the board, Default 6") do |n|
    options[:height] = n
  end

  opts.on('--length N', Integer, "Set winning chain length, Default 4") do |n|
    options[:length] = n
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end

  opts.on_tail('--version', 'Show version') do
    puts CaptainsMistress::VERSION
    exit
  end

end.parse!(args)

CaptainsMistress::App.new(options).run
